name: Deployment Workflow
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh # Название шага: Деплой с использованием SSH
      uses: appleboy/ssh-action@master # Использование готового действия для SSH-подключения
      with:
        host: 147.45.43.248 # Хост (сервер) для подключения, берется из секретов Github
        username: root # Имя пользователя для SSH, берется из секретов Github
        key: ${{ secrets.PRIVATE_KEY }} # Приватный ключ для SSH, берется из секретов Github
        port: 22
        script: |
         cd /root/test/
         git pull origin main
